steps:
  # Prebuild the app image, upload it to a registry for later steps
  - label: ":docker: Build"
    plugins:
      - docker-compose#v1.0.0:
          build: app
          image-repository: index.docker.io/org/repo