steps:
  - name: "Run Docker Compose"
    plugins:
      - docker-compose#v3.0.3:
          run: up

  # Prebuild the app image, upload it to a registry for later steps
  # - label: ":docker: Build"
  #   plugins:
  #     - docker-compose#v1.0.0:
  #         build: app
  #         image-repository: index.docker.io/org/repo

  - wait

  # Use the app image built above to run concurrent tests
  # - label: ":docker: Test %n"
  #   command: test.sh
  #   parallelism: 25
  #   plugins:
  #     - docker-compose#v1.0.0:
  #         run: app