steps:
  - name: "Run Docker Compose"
    parallelism: 2
    plugins:
      - docker-compose#v3.0.3:
          run: cypress
          env:
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT